### PR TITLE
feat: github actions for #10

### LINKED ISSUE #10: Github Actions Master Issue
Create GitHub actions that:
- [x] Build the frontend into an artifact (preferably a .apk file) that can be deployed on a phone
- [x] Build the backend to an executable. 
- [x] Run in-source unit tests on the backend.

### PR DESCRIPTION
**Pull request by akaric108**
as seen on TV

(closes #10)

### CODE REVIEW

**Comment by akaric108** [comment]
couple of findings:
- we cannot build APKs with `RELEASE=1` atm, because of some flutter+gradle+kotlin incompatibilities with some dependencies (read: nonsense). this must be fixed in the future.
- would like to see the github action cache be used, but it isn't that bad for now.

**Review by 10dine — APPROVED** [review]
Looks good, most of it is out of the client folder so not much to review for me.

**Comment by akaric108** [comment]
also, we will probably want to fine-tune the triggers. right now it's manual, but ideally it triggers on PRs and blocks them if they cause the workflow to fail.

i can probably throw that in tomorrow, so ill hold off on merging until then.

**Comment by akaric108** [comment]
once merged, a setting must be changed to activate the `pull_request` trigger

you can find this under the repository's `Settings > Branches`
image

**Pull request merged**
